### ISSUE TITLE
Does it support google maps calculate distance and routing?

### ISSUE THREAD

**Issue by omurbekjk** [ionic-team/ionic-native-google-maps#203]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**Does it support google maps calculate distance and routing?**
If yes, simple examples will be useful.

I wanted to do similar app here: https://www.djamware.com/post/58f4da2080aca7414e78a638/step-by-step-tutorial-of-ionic-3-angular-4-and-google-maps-directions-service?utm_campaign=shareaholic&utm_medium=google_plus&utm_source=socialnetwork

![kaska](https://s3-ap-southeast-1.amazonaws.com/djamblog/article-170417213153.png)

**Comment by wf9a5m75** [comment]
no

**Comment by omurbekjk** [comment]
Just to clarify, it is not possible to add calculating distance and routing to this library, right?
But it can be done using Google Maps JavaScript v3. I read this library was faster than JS v3.

**Comment by wf9a5m75** [comment]
Technically I can implement it, but nobody pay for my time, I don't implement it.

**Comment by omurbekjk** [comment]
So I was curious, why one developer should choose Google JavaScript Library over this library?

**Comment by wf9a5m75** [comment]
It depends on the purpose of developers.

Some developers prefer many features than ability of native SDKs, otherwise some the other developers prefer ability of native SDKs (such as offline) than many features.

This plugin already provides enough necessary basic features, drawing polyline, putting marker, marker clusters...etc.
Also this plugin provides original features, such as HTMLInfoWindow.

So, I guess the most of people are satisfied this plugin. The someone who not satisfied uses Google Maps JavaScript v3.
