### ISSUE TITLE
How to achieve live reload ?

### ISSUE THREAD

**Issue by mluis** [ionic-team/ionic-native-google-maps#275]
**I'm submitting a ...**  (check one with "x")
- [x] question

Is there any versatile development workflow in order to develop with this plugin like live-reloading?

I've tried `ionic cordova build browser && ionic cordova run browser -l` but it doesn't seem to work.

Am I missing something? Thank you.

**Comment by wf9a5m75** [comment]
Maybe you access to `localhost:8080`? Try to access 8100

**Comment by mluis** [comment]
Confirmed. The livereload port is 8100. Closing.

**Comment by battika** [comment]
I know Ionic 3 is no longer supported by this plugin however it still works but here is the command for running browser platform with live reload

> ionic-app-scripts serve --sourceMap source-map --iscordovaserve --wwwDir platforms/browser/www/ --buildDir platforms/browser/www/build

**Comment by awaism551** [comment]
can we achieve livereload incase of emulator/real device?? does this plugin supports livereload in those cases? because currently I am getting this error **Error: Uncaught (in promise): Error: [GoogleMaps]You need to execute "$> ionic cordova run browser"."$> ionic serve" is not supported.** 
obviously this error message is unclear, I am not running `ionic serve` command, I am running `sudo ionic cordova platform run android --livereload` command btw, Thanks
